# Generated by Django 4.2 on 2025-11-25 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
                ('level', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='trainers/')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.trainer'),
        ),
    ]
