# Generated by Django 4.2 on 2025-11-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_trainer_pokemon_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='date_birth',
            new_name='birth_date',
        ),
    ]
